---

################################
# Integrity and confidentiality 
################################# 

  - name: Install aide package (RedHat 6)
    yum:
      state: present
      name: aide
    when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "6"
    register: aide_rhel6

  

  - name: Initialize AIDE
    shell: "{{ scripts_dir }}/aide_init_rhel.sh"
    register: aideinit
    when: info.ansible_facts.ansible_distribution_file_variety == "RedHat"


  - name: AIDE check cron
    cron:
      name: aide check
      month: "*"
      weekday: "*"
      hour: "5"
      user: root
      minute: "0"
      job: "/usr/sbin/aide --check"
