---

  - name: General Security
    hosts: all
    gather_facts: false
    become: true
    become_user: root
    tasks:
      - name: Gather Information
        setup:
        register: info
        tags:
          - always

################################
# Security patches 
################################# 

### SUSE
      
      - name: Check security patches (SUSE)
        shell: "zypper list-updates"
        args:
          warn: false
        when: info.ansible_facts.ansible_distribution_file_variety == "SUSE" 
        register: zypper_check
        ignore_errors: true
        tags:
          - always
  
      - name: Security patch results (SUSE)
        debug:
          var: zypper_check.stdout_lines
        when: info.ansible_facts.ansible_distribution_file_variety == "SUSE" 
        tags:
          - always


      - name: Apply security patches (SUSE)
        shell: zypper update -y
        when: info.ansible_facts.ansible_distribution_file_variety == "SUSE"
        register: security_suse
        tags:
          - never
          - recommend


      

