---

  - name: Useful scripts
    hosts: all
    become: true
    become_user: root
    gather_facts: false
    vars:
      backup_dir: /opt/security-etc-
    tasks:


      - name: Gather Information
        setup:
        register: info
        tags:
          - always

      - name: Create security-etc folder
        file:
          path: "{{ backup_dir }}{{ date }}{{ item }}"
          state: directory
          recurse: true
        with_items:
          - /etc/ssh
          - /usr/lib/systemd/system
          - /etc/security
          - /etc/audit
          - /etc/pam.d/


      - name: Backup config files to backup folder
        copy:
          src: "{{ item }}"
          dest: "{{ backup_dir }}{{ date }}{{ item }}"
          directory_mode:
          remote_src: true
        when: info.ansible_facts.ansible_distribution_file_variety == "SUSE" 
        with_items:
          - /etc/ssh/sshd_config
          - /etc/inittab
          - /etc/login.defs
          - /etc/issue
          - /etc/issue.net
          - /etc/audit/auditd.conf
          - /etc/pam.d/common-password


      - name: Set not to be overwritten 
        shell: "chattr -R +i {{ backup_dir }}{{ date }}{{ item }}"
        with_items:
          - /etc
          - /usr

