---

  - name: Useful scripts
    hosts: all
    become: true
    become_user: root
    gather_facts: false
    tasks:

      - include_vars: config/backup.yaml

      - name: Gather Information
        setup:
        register: info



      - name: Delete remote script directory
        file:
          path: "{{ scripts_parent_dir }}/scripts"
          state: absent



      - name: Copy python scripts
        copy:
          src: scripts
          dest: "{{ scripts_parent_dir }}"
          directory_mode:
          mode: '0550'



      - name: Create security-etc folder
        file:
          path: "{{ backup_dir }}{{ info.ansible_facts.ansible_date_time.date }}{{ item }}"
          state: directory
          recurse: true
        with_items:
          - /etc/ssh
          - /etc/security
          - /etc/audit
          - /etc/pam.d/
          - /etc/sysconfig/
          - /usr/lib/systemd/system
          - /boot/grub/


      - name: Backup config files to backup folder (RedHat 7/8)
        copy:
          src: "{{ item }}"
          dest: "{{ backup_dir }}{{ info.ansible_facts.ansible_date_time.date }}{{ item }}"
          directory_mode:
          remote_src: true
        when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and (info.ansible_facts.ansible_distribution_major_version == "7" or info.ansible_facts.ansible_distribution_major_version == "8")
        with_items:
          - /etc/ssh/sshd_config
          - /usr/lib/systemd/system/rescue.service
          - /usr/lib/systemd/system/emergency.service
          - /etc/security/pwquality.conf
          - /etc/login.defs
          - /etc/issue
          - /etc/issue.net
          - /etc/audit/auditd.conf
          - /etc/pam.d/system-auth 
          - /etc/pam.d/password-auth


      - name: Backup config files to backup folder (RedHat 6)
        copy:
          src: "{{ item }}"
          dest: "{{ backup_dir }}{{ info.ansible_facts.ansible_date_time.date }}{{ item }}"
          directory_mode:
          remote_src: true
        when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "6"
        with_items:
          - /etc/sysconfig/init
          - /etc/ssh/sshd_config
          - /boot/grub/grub.conf
          - /etc/pam.d/system-auth
          - /etc/pam.d/password-auth
          - /etc/login.defs
          - /etc/issue
          - /etc/issue.net
          - /etc/audit/auditd.conf


      - name: Backup config files to backup folder (SUSE 11)
        copy:
          src: "{{ item }}"
          dest: "{{ backup_dir }}{{ info.ansible_facts.ansible_date_time.date }}{{ item }}"
          directory_mode:
          remote_src: true
        when: info.ansible_facts.ansible_distribution_file_variety == "SUSE" 
        with_items:
          - /etc/ssh/sshd_config
          - /etc/inittab
          - /etc/login.defs
          - /etc/issue
          - /etc/issue.net
          - /etc/audit/auditd.conf
          - /etc/pam.d/common-password



      - block:
        - name: Install libpwquality-tools, auditd (Debian)
          apt:
            name: ['libpwquality-tools', 'auditd']
            state: present


        - name: Backup config files to backup folder (Debian)
          copy:
            src: "{{ item }}"
            dest: "{{ backup_dir }}{{ info.ansible_facts.ansible_date_time.date }}{{ item }}"
            directory_mode:
            remote_src: true
          with_items:
            - /etc/ssh/sshd_config
            - /usr/lib/systemd/system/rescue.service
            - /usr/lib/systemd/system/emergency.service
            - /etc/security/pwquality.conf
            - /etc/login.defs
            - /etc/issue
            - /etc/issue.net
            - /etc/audit/auditd.conf
        when: info.ansible_facts.ansible_distribution_file_variety == "Debian" 



      - name: Set not to be overwritten 
        shell: "chattr -R +i {{ backup_dir }}{{ info.ansible_facts.ansible_date_time.date }}{{ item }}"
        with_items:
          - /etc
          - /usr

