---

################################
# Security patches 
################################# 

### RedHat 7
      
  - name: Check security patches (RedHat 7)
    shell: "yum check-update"
    args:
      warn: false
    when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "7"
    register: yum_check
    changed_when: "yum_check.rc == 100"
    ignore_errors: true


  - name: Security patch results (RedHat 7)
    debug:
      var: yum_check.stdout_lines
    when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "7" 


  - name: Apply security patches (RedHat 7)
    shell: yum update --security -y
    when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "7"
    register: security_rhel7


### RedHat 8

  - name: Check security patches (RedHat 8)
    shell: "dnf check-update --security"
    args:
      warn: false
    when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "8"
    register: dnf_check
    ignore_errors: true
    changed_when: "dnf_check.rc == 100"


  - name: Security patch results (RedHat 8)
    debug:
      var: dnf_check.stdout_lines
    when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "8"


  - name: Apply security patches (RedHat 8)
    shell: "dnf update --security -y"
    args:
      warn: false
    when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "8"
    register: security_rhel8
  

