---

  - name: Find priviledged executable files
    shell: find / -xdev -perm -4000 -o -perm 2000
    register: exec_file


  - name: Find minimum user uid
    shell: awk '/^\s*UID_MIN/{print $2}' /etc/login.defs
    register: uid


  - name: Create audit record inside audit rules
    lineinfile:
      path: /etc/audit/rules.d/non-privledged.rules
      line: "-a always,exit -F path={{ item }} -F perm=x -F auid>={{ uid.stdout_lines[0] }} -F auid!=4294967295 -k privileged"
      create: true
    with_items: "{{ exec_file.stdout_lines }}"
    when: exec_file.rc == 0 and uid.rc == 0


  - name: Install sudo package (RedHat 7)
    yum:
      state: present
      name: sudo
    when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "7"


  - name: Install sudo package (RedHat 8)
    yum:
      state: present
      name: sudo
    when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "8"


#############################
# Authorization Configuration 
#############################

# ignore remote hosts on SSH


  - name: Verify ignore remote hosts on SSH
    shell: sshd -T | grep ignorerhosts | grep yes
    register: vremote
    ignore_errors: true


  - name: Confirm ignore remote hosts on SSH
    debug:
      msg: "Ignore remote hosts is enabled on SSH"
    when: vremote.rc == 0


  - name: Configure ignore remote hosts on SSH
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '[#|\s]*IgnoreRhosts\s+[yes|no]'
      line: "IgnoreRhosts yes"
      state: present
    register: remotehost01
    when: vremote.rc != 0


  - name: Verify root login is disabled on SSH
    shell: sshd -T | grep permitrootlogin | grep no
    register: vrootlog
    ignore_errors: true


  - name: Confirm root login is disabled on SSH 
    debug: 
      msg: "Permit root login is disabled on SSH"
    when: vrootlog.rc == 0



  - name: Disable root login on SSH
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '[#|\s]*PermitRootLogin\s+[yes|no]'
      line: "PermitRootLogin no"
      state: present
    register: permitroot01
    when: vrootlog.rc != 0


  - name: Allow only certain users on SSH
    lineinfile:
      path: /etc/ssh/sshd_config
      line: "AllowUsers {{ ssh_user }}"
      state: present


  - name: Permissions on sshd_config file
    shell: "chown root:root {{ item }} && chmod 0600 {{ item }}"
    args:
      warn: false
    with_items:
      - /etc/ssh/sshd_config


  - name: Restart SSH service
    systemd:
      state: reloaded 
      name: sshd



    
