---

  - name: General Security
    hosts: all
    gather_facts: false
    become: true
    become_user: root
    tasks:
      - name: Gather Information
        setup:
        register: info
        tags:
          - always

################################
# Security patches 
################################# 

### RedHat 6
      
      - name: Check security patches (RedHat 6)
        shell: "yum check-update"
        args:
          warn: false
        when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "7"
        register: yum_check
        changed_when: "yum_check.rc == 100"
        ignore_errors: true
        tags:
          - always
  
      - name: Security patch results (RedHat 6)
        debug:
          var: yum_check.stdout_lines
        when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "6" 
        tags:
          - always


      - name: Apply security patches (RedHat 6)
        shell: yum update -y
        when: info.ansible_facts.ansible_distribution_file_variety == "RedHat" and info.ansible_facts.ansible_distribution_major_version == "6"
        register: security_rhel7
        tags:
          - never
          - recommend


      

